os: osx
language: shell  # 'language: python' is not yet supported on macOS
cache: pip
matrix:
  include:
    - name: "Python 3.7 on macOS default xcode 9.4.1 "
    - name: "Python 3.7 on macOS xcode10"
      osx_image: xcode10
    - name: "Python 3.7 on macOS xcode10.1"
      osx_image: xcode10.1
    - name: "Python 3.7 on macOS xcode10.2.1"
      osx_image: xcode10.2
    - name: "Python 3.7 on macOS xcode11"
      osx_image: xcode11

env: NODE_GYP_FORCE_PYTHON=python3 EXPERIMENTAL_NODE_GYP_PYTHON3=1
before_install: HOMEBREW_NO_AUTO_UPDATE=1 brew install npm
install:
  #- pip install -r requirements.txt
  - pip install flake8  # pytest  # add another testing frameworks later
before_script:
  - flake8 --version
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  Two space indentation is OK.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --ignore=E111,E114,W503 --max-complexity=10 --max-line-length=127 --statistics
  - xcode-select --install
  - npm install
script:
  - node -e 'require("npmlog").level="verbose"; require("./lib/find-python")(null,()=>{})'
  - npm test
  #- pytest --capture=sys  # add other tests here
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
